lanterns:
  - id: 0
    name: Lantern
    lore: []
    light:
      - 0
      - 15
    textures:
      - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzZlOTM4NTNmZWMxODdlMTkwYWJkNWUwMTcxN2IyZTE1YzE1ZmU2MGJmMzVhZmEzNGJkMTc2YmRiOGFjNzdiIn19fQ==
      - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODc5ODY5YTk4N2I4MmVjMjkzYWUzNDUxOTc2YjZhMWQ4MjFkZWUwZDhiZTdiMzkxOWY4YWQ5Y2M4ZTU1OGE1MiJ9fX0=
  - id: 1
    name: Traffic Light
    lore: []
    light:
      - 4
      - 8
      - 12
    textures:
      - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMzRkNDZjM2ZmODhlMGRiYzUxZjY2MjE5M2UxOWViNGEwMWNkMWY0MGFkZDNhMWJiMTU2NjcwOTlhOGJiYjIifX19
      - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzk1MGRlMzg0M2UwNmIzM2ZmYzMzNGMxNTRiZjliMzk4ODgxNWM3ZTU0NjM2MjM3N2ZlN2EwNzQzNmFiIn19fQ==
      - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmZkYzRjODg5NWUzZjZiM2FjNmE5YjFjZDU1ZGUzYTI5YmJjOGM3ODVlN2ZiZGJkOTMyMmQ4YzIyMzEifX19
  - id: 2
    name: Jack O Lantern
    lore: []
    light:
      - 0
      - 8
    textures:
      - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvN2FlZTc1MzgwNjlkMzlmM2U1NDk5NGY0MWU3ZGY3ZDVjM2I4MjMxYmMwMDQxZDc0NTgyMzA2NjMzMTRmMjhjIn19fQ==
      - eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZmY2ZGMzNDkzZTk3ZDBlNzE4YTE2ZjY1YTA1MWY5YzM3Mjg5NDkxZDcwNzVmMTQzN2E2M2UzYmJmZTkxNDAxOCJ9fX0=
