name: Lantern
version: '${version}'
main: io.github.fhanko.lantern.Lantern
api-version: '1.20'

commands:
  lantern:
    description: "Adds lantern with <id> to your inventory."
    usage: "/lantern <id>"
